version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10-browsers

    working_directory: ~/project

    steps:
    - checkout

    - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: yarn install

    - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
          - node_modules

    - run:
        name: Linting
        command: yarn lint

    - run:
        name: Testing
        command: yarn test

    - run:
        name: Building
        command: |
          if [ ${CIRCLE_BRANCH} == 'staging' ]; then
            yarn build-qa
          elif [ ${CIRCLE_BRANCH} == 'master' ]; then
            yarn build-prod
          else
            yarn build-dev
          fi

    - save_cache:
            key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            paths:
            - dist
